name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Mictodo to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Deplot Mictodo to Vercel
        uses: amondnet/vercel-action@v20.0.1
        # Docs: https://github.com/marketplace/actions/vercel-action#github-actions
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
