name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
jobs:
  test:
    name: E2E Testing with Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Cypreen Run
        uses: cypress-io/github-action@v2
        env:
          LOCAL_STORAGE_KEY: ${{ secrets.CYPRESS_LOCAL_STORAGE_KEY }}
          LOCAL_STORAGE_VALUE: ${{ secrets.CYPRESS_LOCAL_STORAGE_VALUE }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_API_KEYS: ${{ secrets.NEXT_PUBLIC_SUPABASE_API_KEYS }}
          NEXT_PUBLIC_IS_DEVELOPMENT: ${{ secrets.NEXT_PUBLIC_IS_DEVELOPMENT }}
          NEXT_PUBLIC_IS_RELEASE_FEATURE: ${{ secrets.NEXT_PUBLIC_IS_RELEASE_FEATURE }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          start: yarn run dev:app
          spec: |
            cypress/integration/features/login.spec.ts
            cypress/integration/features/task-group.spec.ts
            cypress/integration/features/task-item.spec.ts
          browser: chrome
  deploy:
    name: Deploy Mictodo to Vercel
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Deploy to Production
        uses: amondnet/vercel-action@v20.0.1
        # Docs: https://github.com/marketplace/actions/vercel-action#github-actions
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
